### ISSUE TITLE
New business rule required

### ISSUE THREAD

**Issue by lemendoza** [avmurrie/ISII-WORKSHOP2-TRANSPORTER#5]
**Is your feature request related to a problem? Please describe.**
Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rull beginning january 2021

**Describe the solution you'd like**
If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

**Describe alternatives you've considered**
We ask you to modify the premium calculation adding this new rule.

**Additional context**

**Comment by avmurrie** [comment]
New rule accepted

**Comment by avmurrie** [comment]
Issue categorization

**Comment by avmurrie** [comment]
**Issue assignment**

> Analyst: @edisonrosales 
> Programmer: @UDannyf 
> Tester: @bsantos97

**Comment by edisonrosales** [comment]
The impact analysis has been carried out, we estimate one day to add the new requirement to the system because the new conditional needs to be added to the function in charge of calculating the premium and, additionally, the respective software tests must be carried out.

**Comment by lemendoza** [comment]
Ok, proceed.

**Comment by U-Danny** [comment]
https://github.com/avmurrie/ISII-WORKSHOP2-TRANSPORTER/blob/fb87348427890297229f95e34af4af98668e36ea/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L65-L67

**Comment by bsantos97** [comment]
Dear @lemendoza  , the following test plan details the results obtained after applying the solution to the identified problem. We want to know if this is the result you expect to get when you add the new rule.
[testPlan.pdf](https://github.com/avmurrie/ISII-WORKSHOP2-TRANSPORTER/files/5852592/testPlan.pdf)

**Comment by lemendoza** [comment]
Yes, those are the results I expect.

**Comment by bsantos97** [comment]
Dear @lemendoza , then you take this solution for accepted?

**Comment by lemendoza** [comment]
Yes, I accept.

**Comment by avmurrie** [comment]
@lemendoza the solution has been completed and @UDannyf  will release the new software version for you

**Comment by edisonrosales** [comment]
Dear @lemendoza ,
The new version of the software is already available in the repository, the execution process has not changed compared to previous versions. You must download the repository and execute the "main" class and enter the necessary parameters to obtain the result.

**Comment by lemendoza** [comment]
Ok.

**Comment by avmurrie** [comment]
Dear @lemendoza, we will expect your response about the use and satisfaction with the implemented solution and If all is ok, we will close the issue.

**Comment by lemendoza** [comment]
Yes, I satisfied with the implemented solution.
